Mudeer/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from POSsystem import views 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('welcome/', views.welcome, name="welcome"),
    path('profile/', views.profile, name='profile_page'),
    path('detail/<int:restaurant_id>/', views.business_detail, name='detail'),
    path('ordering_page/<int:restaurant_id>/', views.ordering_page, name='ordering_page'),

    path('categoryDetails/<int:category_id>/', views.categoryDetails, name='categoryDetails'),
    path('addCategory/<int:restaurant_id>/', views.addCategory, name='addCategory'),
    path('update_category/<int:category_id>/', views.updateCategory, name='update_category'),
	path('delete_category/<int:category_id>/', views.delete_category, name='delete_category'),


    path('addItem/<int:category_id>/', views.addItem, name='addItem'),
    path('update_item/<int:item_id>/', views.updateItem, name='update_item'),
    path('delete_item/<int:item_id>/', views.delete_item, name='delete_item'),
    # path('welcome2/', views.welcome, name="welcome2"),

    # User authentication related URLS
    path('register/', views.user_register, name="register"),
    path('login/', views.user_login, name="login"),
	path('logout/', views.userlogout, name='logout'),


	path('create/', views.create, name="create_rest"),
	path('update/<int:restaurant_id>/', views.update, name="update_rest"),
	path('delete/<int:restaurant_id>/', views.delete, name="delete_rest"),

	path('order/<int:item_id>/', views.order, name='order'),
	path('view_order/<int:restaurant_id>/', views.view_order, name='view_order'),

]

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

POSsystem/models.py
from django.db import models
from django.contrib.auth.models import User

class Restaurant(models.Model):
	name = models.CharField(max_length=25)
	image = models.ImageField()
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	description = models.TextField()
	established = models.DateField(auto_now_add=True)


	def __str__(self):
		return "Name: [" + self.name + "] " + self.description



class Category(models.Model):
	restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
	name = models.CharField(max_length=25)

	def __str__(self):
		return "Name: " + self.name 


class Item(models.Model):
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	name = models.CharField(max_length=25)
	description = models.TextField()
	price = models.DecimalField(max_digits=5, decimal_places=3)

	def __str__(self):
		return "Name: " + self.name 

class OrderItem(models.Model):
	order = models.ForeignKey('Order', on_delete=models.CASCADE)
	item = models.ForeignKey(Item, on_delete=models.CASCADE)
	quantity = models.PositiveIntegerField(default=1)
	item_total = models.DecimalField(decimal_places = 3, max_digits = 6,default=0)
	timestamp = models.DateTimeField(auto_now=True)

class Order(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	items = models.ManyToManyField(Item, through=OrderItem)
	total = models.DecimalField(max_digits=6, decimal_places=3, default=0.0)
	dinner = models.BooleanField(default=False)
	complete = models.BooleanField(default=False)


	def get_total(self):
		order_items = self.orderitem_set.all()
		total = 0
		for item in order_items:
			total += (item.quantity * item.item.price)
		return total

	
	

POSsystem/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Restaurant, Category, Item


class UserRegisterForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'first_name', 'last_name', 'password']
		widgets = {
			"password": forms.PasswordInput()
		}

class LoginForm(forms.Form):
	username = forms.CharField(required=True)
	password = forms.CharField(required=True, widget=forms.PasswordInput())


class RestaurantForm(forms.ModelForm):
	class Meta:
		model = Restaurant
		fields = '__all__'
		exclude =['owner']

class CategoryForm(forms.ModelForm):
	class Meta:
		model = Category
		fields = '__all__'
		exclude =['restaurant']

class ItemForm(forms.ModelForm):
	class Meta:
		model = Item
		fields = '__all__'
		exclude =['category']

POSsystem/views.py
from django.shortcuts import render, redirect
from .forms import UserRegisterForm, LoginForm, RestaurantForm, CategoryForm, ItemForm
from django.contrib.auth import authenticate, login, logout
from .models import Restaurant, Category, Item, Order, OrderItem
from django.http import Http404, JsonResponse
from django.db.models import Q
import json
from django.contrib.auth.decorators import login_required


def user_register(request):
	form = UserRegisterForm()
	if request.method == "POST":
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			user = form.save()
			my_user = user.username
			my_password = user.password
			user.set_password(user.password)
			user.save()
			
			login(request, user)
			return redirect("welcome")
	context = {
		"form": form
	}
	return render(request, 'register.html', context)

def user_login(request):
	form = LoginForm()
	if request.method == "POST":
		form = LoginForm(request.POST)
		if form.is_valid():
			my_username = form.cleaned_data['username']
			my_password = form.cleaned_data['password']
			auth_user = authenticate(username=my_username, password=my_password)
			if auth_user is not None:
				login(request, auth_user)
				return redirect("profile_page")
	context = {
		"form": form
	}
	return render(request, 'login.html', context)

def userlogout(request):
    logout(request)
    return redirect("welcome")

def welcome(request):

	if not request.user.is_authenticated:
		return render(request, "main.html", {})
	else:
		return render(request, "welcome.html", {})


@login_required(login_url='/login/')
def profile(request):
	if request.user.is_anonymous:
		return redirect('login')


	restaurants = Restaurant.objects.all()
	restaurants = restaurants.order_by('name', 'established')
	owner_name = request.user
	if not(request.user.is_staff):
		restaurants = restaurants.filter(owner=owner_name)

	query = request.GET.get('q')
	if query:
		restaurants = restaurants.filter(owner__username__contains=query)
	

	context = {
		"restaurants": restaurants,
		}
	return render(request, 'profile_page.html', context)

@login_required(login_url='/login/')
def business_detail(request, restaurant_id):
	restaurant_obj = Restaurant.objects.get(id=restaurant_id)
	context = {
		"restaurant_obj": restaurant_obj,
	}
	return render(request, 'detail.html', context)


@login_required(login_url='/login/')
def create(request):
	restaurant_form = RestaurantForm()
	if request.method == "POST":
		restaurant_form = RestaurantForm(request.POST, request.FILES)
		if restaurant_form.is_valid():
			restaurant = restaurant_form.save(commit=False)
			restaurant.owner=request.user
			restaurant.save()
			

			return redirect("profile_page")
	context = {
		"restaurant_form": restaurant_form,
		
	}
	return render(request, 'create_rest.html', context)

def update(request, restaurant_id):
	restaurant_obj = Restaurant.objects.get(id=restaurant_id)
	if not(request.user.is_staff or request.user==restaurant_obj.owner):
		# return HttpResponse("<h1>Error you are not the owner of the restaurant or staff member</h1>")
		raise Http404("You don't have permission")
	form = RestaurantForm(instance=restaurant_obj)
	if request.method == "POST":
		form = RestaurantForm(request.POST, request.FILES, instance=restaurant_obj)
		if form.is_valid():
			form.save()
			return redirect("profile_page")
	context = {
		"form": form,
		"restaurant_obj": restaurant_obj,
	}
	return render(request, 'update_rest.html', context)

def delete(request, restaurant_id):
	restaurant_obj = Restaurant.objects.get(id=restaurant_id)
	if not (request.user.is_staff or request.user==restaurant_obj.owner):
		# return HttpResponse("<h1>You don't have the permission to delete the restaurant</h1>")
		raise Http404("You don't have permission")
	Restaurant.objects.get(id=restaurant_id).delete()
	
	return redirect("profile_page")


def categoryDetails(request, category_id):
	context = {
		"category": Category.objects.get(id=category_id)
		}
	return render(request, 'categoryDetails.html', context) 



def addCategory(request, restaurant_id):
	restaurant_obj = Restaurant.objects.get(id=restaurant_id)
	if not(request.user.is_staff or request.user==restaurant_obj.owner):
		# return HttpResponse("<h1>Error you are not the owner of the restaurant or staff member</h1>")
		raise Http404("You don't have permission")
	
	category_form = CategoryForm()
	if request.method == "POST":
		category_form = CategoryForm(request.POST)
		
		
		if category_form.is_valid():
			category = category_form.save(commit=False)
			category.restaurant = restaurant_obj
			category.save()
			if request.POST.get("save"):
				return redirect("addCategory", restaurant_id=restaurant_obj.id)
			else:
				return redirect("detail",restaurant_id=restaurant_obj.id)
		
	context = {
		"restaurant_obj": restaurant_obj,
		"category_form": category_form,
	}
	return render(request, 'addCategory.html', context)

def updateCategory(request, category_id):
	category_obj = Category.objects.get(id=category_id)
	if not(request.user.is_staff or request.user==category_obj.restaurant.owner):
		# return HttpResponse("<h1>Error you are not the owner of the restaurant or staff member</h1>")
		raise Http404("You don't have permission")
	form = CategoryForm(instance=category_obj)
	if request.method == "POST":
		form = CategoryForm(request.POST, instance=category_obj)
		if request.POST.get("cancel"):
				return redirect("detail",restaurant_id=category_obj.restaurant.id)
		else:
			form.is_valid()
			form.save()
			return redirect("detail",restaurant_id=category_obj.restaurant.id)
	context = {
		"form": form,
		"category_obj": category_obj,
	}
	return render(request, 'update_category.html', context)

def delete_category(request, category_id):
	category_obj = Category.objects.get(id=category_id)
	if not (request.user.is_staff or request.user==category_obj.restaurant.owner):
		# return HttpResponse("<h1>You don't have the permission to delete the restaurant</h1>")
		raise Http404("You don't have permission")
	Category.objects.get(id=category_id).delete()
	
	return redirect("detail",restaurant_id=category_obj.restaurant.id)


def addItem(request, category_id):
	category_obj = Category.objects.get(id=category_id)
	restaurant_obj = Restaurant.objects.get(id=category_obj.restaurant.id)
	if not(request.user.is_staff or request.user==restaurant_obj.owner):
		# return HttpResponse("<h1>Error you are not the owner of the restaurant or staff member</h1>")
		raise Http404("You don't have permission")
	category_obj = Category.objects.get(id=category_id)
	item_form = ItemForm()
	if request.method == "POST":
		item_form = ItemForm(request.POST)
		if item_form.is_valid():
			item = item_form.save(commit=False)
			item.category = category_obj
			item.save()
			if request.POST.get("save"):
				return redirect("addItem", category_id=category_obj.id)
			else:
				return redirect("detail",restaurant_id=category_obj.restaurant.id)

	
	context = {
		"category_obj": category_obj,
		"item_form": item_form,
	}
	return render(request, 'addItem.html', context)

def updateItem(request, item_id):
	item_obj = Item.objects.get(id=item_id)
	if not(request.user.is_staff or request.user==item_obj.category.restaurant.owner):
		# return HttpResponse("<h1>Error you are not the owner of the restaurant or staff member</h1>")
		raise Http404("You don't have permission")
	form = ItemForm(instance=item_obj)
	if request.method == "POST":
		form = ItemForm(request.POST, instance=item_obj)
		if request.POST.get("cancel"):
				return redirect("detail",restaurant_id=item_obj.category.restaurant.id)
		else:
			form.is_valid()
			form.save()
			return redirect("detail",restaurant_id=item_obj.category.restaurant.id)
	context = {
		"form": form,
		"item_obj": item_obj,
	}
	return render(request, 'update_item.html', context)

def delete_item(request, item_id):
	item_obj = Item.objects.get(id=item_id)
	if not (request.user.is_staff or request.user==item_obj.item.restaurant.owner):
		# return HttpResponse("<h1>You don't have the permission to delete the restaurant</h1>")
		raise Http404("You don't have permission")
	Item.objects.get(id=item_id).delete()
	
	return redirect("detail",restaurant_id=item_obj.category.restaurant.id)


def ordering_page(request,restaurant_id):
	restaurant_obj = Restaurant.objects.get(id=restaurant_id)
	
	items = OrderItem.objects.all()

	order_list = []

	for item in items:
		order_list.append(item)
	

	context = {
		"restaurant": restaurant_obj,
		"order_list": order_list,
	}
	return render(request, 'ordering_page.html', context)

def order(request, item_id):
	item_obj = Item.objects.get(id=item_id)
	order = Order.objects.filter(user=request.user, complete=False)

	qty = request.GET.get('qty', 1)

	if order.exists():
		order_obj=order.first()
	else:
		order_obj = Order.objects.create(user=request.user)
	

	item, create = OrderItem.objects.get_or_create(order=order_obj, item=item_obj)

	if create:
		print('created')
		item.quantity = qty
		item.save()
	else:
		if int(qty) < 1:
			item.delete()
		else:
			item.quantity += 1
			item.save()
	

	order_items = []
	
	for order_item in order_obj.orderitem_set.all():
		order_items.append({
			"id":order_item.item.id,
			"name":order_item.item.name,
			"quantity": order_item.quantity,
			"price": order_item.item.price * order_item.quantity,
			})
	return JsonResponse(order_items, safe=False)

# def removeItem(request, item_id):


def view_order(request, restaurant_id):
	restaurant_obj = Restaurant.objects.get(id=restaurant_id)

	orderItems = OrderItem.objects.all()
	order_obj = Order.objects.get(user=request.user, complete=False)
	
	order_item_list = []
	for order_item in order_obj.orderitem_set.all():
		order_item_list.append({
			"id":order_item.item.id,
			"name":order_item.item.name,
			"quantity": order_item.quantity,
			"price": order_item.item.price * order_item.quantity,
			})
	order_total = order_obj.get_total()
	order_obj.complete = removeOrderItems(order_obj.id)
	

	context = {
		'restaurant': restaurant_obj,

POSsystem/templates/addCategory.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block tilte %}
Create Category
{% endblock %}

{% block content %}
<div class="container">
	<br>
	<h2> Adding category to a restaurant :</h2>
	
	<div class="col-md-12 bg-dark mt-3 md-3 px-3 p-3">
		<form class="jumbotron border border-primary" action="{% url 'addCategory' restaurant_id=restaurant_obj.id %}" method="POST">
			<div class="col-md-12">
				<h1 class="ml-3"><strong>Restaurant name : {{restaurant_obj.name}}</strong></h1>
			</div>
		{% csrf_token %}
		{{category_form|crispy}}
		<input type="submit" name="save" value="Save & Add Another" class="btn btn-primary">
		<input type="submit" name="create" value="Save" class="btn btn-success">
		<a href="{% url 'detail' restaurant_obj.id %}" class="btn btn-danger">Cancel</a>
	</form>
</div>
</div>
{% endblock content %}

POSsystem/templates/addItem.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block tilte %}
Create item
{% endblock %}

{% block content %}
<div class="container">
	
	<div class="col-md-12">
		<h1 class="mt-5 ml-3"><strong>Category name : {{category_obj.name}}</strong></h1>
	</div>
	<br>
	<div class="col-md-12 bg-dark mt-3 md-3 px-3 p-3">
		<form class="jumbotron border border-primary" action="{% url 'addItem' category_id=category_obj.id %}" method="POST">
			<h2> Adding item to a category :</h2>
	<br>
		{% csrf_token %}
		{{item_form|crispy}}
		<input type="submit" name="save" value="Save & Add Another" class="btn btn-primary">
		<input type="submit" name="create" value="Save" class="btn btn-success">
		<a href="{% url 'detail' category_obj.restaurant.id %}" class="btn btn-danger">Cancel</a>
	</form>
</div>
</div>
{% endblock content %}

POSsystem/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


  
  

    <title>
    {% block title %}

    {% endblock title %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/shop-homepage.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.11/css/all.css" integrity="sha384-p2jx59pefphTFIpeqCcISO9MdVfIm4pNnsL08A6v5vaQc4owkQqxMV8kg4Yvhaw/" crossorigin="anonymous">


    


  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top ">
      <div class="container">
        <a class="navbar-brand mr-5" href="{% url 'welcome' %}"><strong>Mudeer</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <ul class="navbar-nav ml-5 ">
            <li class="nav-item active">
              <a class="nav-link btn btn-outline-primary" href="{% url 'profile_page' %}">Profile
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li>
            {% if "/detail/" in request.path %}
            <a class="nav-link btn btn-outline-primary ml-3 text-white" href="{% url 'ordering_page' restaurant_id=restaurant_obj.id %}"> Ordering Page</a>
            {% endif %} 
            </li>
          </ul>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="nav navbar-nav navbar-right ml-auto">
            {% if user.is_staff and "/profile" in request.path %}
            <li>
                <form class="form-inline">
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <button class="btn btn-primary my-2 my-sm-0 input-group-text" id="basic-addon1">@</span>
                    </div>
                    <input class="form-control mr-sm-2" type="search" placeholder="Search for User" aria-label="Search" name="q">
                  </div>
                </form>
            </li>
            {% endif %}
          {% if not user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link btn btn-outline-primary text-white" href="{% url 'register' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link btn btn-outline-primary text-white ml-3" href="{% url 'login' %}">Login</a>
            </li>
            {% else %}
            <li class="nav-item mr-5">
              <a class="nav-link text-white ml-5">Username : <strong>{{user.username}}</strong> </a>
            </li>
            <li class="nav-item">
              <a class="nav-link btn btn-outline-primary text-white" href="{% url 'logout' %}">Logout</a>
            </li>
          </ul>
          {% endif %}
        </div>
      </div>
    </nav>
    <div class="container col-md-9" >
    {% block content %}
    

    
    
    {% endblock content %}
    </div>

    <!-- Footer -->
    <div class="row">
    <footer class="mt-5 bg-dark col-md-12 col-sm-12 sticky-bottom" >
      <div class="container">
        <p class="text-center text-white mt-3">Copyright &copy; Mudeer 2018</p>
      </div>
      <!-- /.container -->
    </footer>
    </div>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>




  </body>

</html>

POSsystem/templates/categoryDetails.html
{% extends "base.html" %}


{% block title %}
  Category detail
{% endblock %}

{% block content %}

<p>Category Name : {{category.name}}</p>


	
	{% for item in category.item_set.all %}
	
	<div class="card-deck ml-3 mt-3 ">
	  <div class="card col-md-4">
	    <div class="card-body">
	      <h5 class="card-title"> <strong> {{item.name}} </strong></h5>
	      <p class="card-text"><strong>Description :</strong> {{item.description}}</p>
	      <p class="card-text text-danger"><small class="">Price : {{item.price}} KWD</small></p>
	    </div>
	  </div>
	  <a href="{% url 'update_item' item_id=item.id %}"><button type="button" class="ml-5 mt-5 mx-auto btn btn-primary">Edit Item</button></a>
	  
	</div>
	
	 {% endfor %}

	<a href="{% url 'detail' restaurant_id=category.restaurant.id %}"><button type="button" class="ml-3 mr-5 mt-5 btn btn-primary btn-lg">Back</button></a>






{% endblock content %}

POSsystem/templates/detail.html
{% extends "base.html" %}

{% block tilte %}
Buisiness Detail
{% endblock %}

{% block content %}

	 
	<div class="col-md-12">
		<img class="card-img-top1 mt-3 ml-5" src={{restaurant_obj.image.url}} alt="Card image cap">
		
		<h1 class=" ml-3"><strong>Restaurant name : {{restaurant_obj.name}}</strong></h1>
	</div>
	<div class="col-md-12">
	<div class="col-sm-12 col-md-12 col-lg-12 mt-5 mb-5">
		<div class="mx-auto" style="width: 200px;">
			<a href="{% url 'addCategory' restaurant_id=restaurant_obj.id %}"><button type="button" class="ml-3 mr-5 mt-5 btn btn-success mx-middle btn-lg fas fa-plus-circle">  Add New Category</button></a>
		</div>
	</div>
	
		
		<h3 class="ml-5 mt-5">Menu :</h3>
		
	</div>

		<br>
		
		{%for category in restaurant_obj.category_set.all%}
			<div class="jumbotron border border-success">
			<h1 class="alert alert-success mx-auto">[{{category.name}}]</h1>
				<a href="{% url 'update_category' category_id=category.id %}"><button type="button" class="ml-5 mx-auto btn btn-primary btn-lg fas fa-cogs">  Edit Category Name</button></a>
					<button type="button" class="ml-5 mx-auto btn btn-danger btn-lg fas fa-trash-alt" data-toggle="modal" data-target="#deleteModal-{{category.id}}">
						DELETE
					</button>
				<div class="modal fade" id="deleteModal-{{category.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
				  <div class="modal-dialog" role="document">
				    <div class="modal-content">
				      <div class="modal-header">
				        <h5 class="modal-title" id="exampleModalLabel">Do you want to Delete {{category.name}}?</h5>
				        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
				          <span aria-hidden="true">&times;</span>
				        </button>
				      </div>
				      <div class="modal-footer">
				        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				        <a href="{% url 'delete_category' category_id=category.id %}">
				        	<button type="button" class="btn btn-danger">
				        	Delete
				        	</button>
				        </a>
				      </div>
				    </div>
				  </div>
				</div>

				<a href="{% url 'addItem' category_id=category.id %}"><button type="button" class="ml-5 mx-auto btn btn-success btn-lg fas fa-plus-circle">  Add Item </button></a>

			<br>
			{%for item in category.item_set.all%}
			<hr style="height:2px;background-color:black;border:none;" noshade />
			<div class="card-deck ml-3 mt-3 ">
			  <div class="card col-md-4">
			    <div class="card-body">
			      <h5 class="card-title"> <strong> {{item.name}} </strong></h5>
			      <p class="card-text"><strong>Description :</strong> {{item.description}}</p>
			      <p class="card-text text-danger"><small class="">Price : {{item.price}} KWD</small></p>
		        </div>
	  		  </div>
	  		  <div>
	  			<a href="{% url 'update_item' item_id=item.id %}"><button type="button" class="ml-5 mt-5 btn btn-primary fas fa-cogs">  Edit Item</button></a>
	  		  </div>

	  		  
	  			<a href="#">
	  			<button type="button" class="ml-2 mt-5 btn btn-danger fas fa-trash-alt " data-toggle="modal" data-target="#deleteModal-{{item.id}}">  Delete Item</button>
	  			</a>
	  			<div class="modal fade" id="deleteModal-{{item.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
				  <div class="modal-dialog" role="document">
				    <div class="modal-content">
				      <div class="modal-header">
				        <h5 class="modal-title" id="exampleModalLabel">Do you want to Delete {{item.name}}?</h5>
				        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
				          <span aria-hidden="true">&times;</span>
				        </button>
				      </div>
				      <div class="modal-footer">
				        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				        <a href="{% url 'delete_item' item_id=item.id %}">
				        	<button type="button" class="btn btn-danger">
				        	Delete
				        	</button>
				        </a>
				      </div>
				    </div>
				  </div>
				</div>
	  	      
			
			
			</div>
			<hr style="height:2px;background-color:black;border:none;" noshade />
			{%endfor%}
			</div>
			
		{%endfor%}

	
	<div class="col-sm-12 col-md-12 col-lg-12 mt-5 mb-5">
		<div class="mx-auto" style="width: 200px;">
			<a href="{% url 'addCategory' restaurant_id=restaurant_obj.id %}"><button type="button" class="ml-3 mr-5 mt-5 btn btn-success mx-middle btn-lg fas fa-plus-circle"> Add New Category</button></a>
		</div>
	</div>
	<div class="col-sm-12 col-md-12 col-lg-12 mt-5 mb-5">
			
				<a href="{% url 'profile_page' %}"><button type="button" class="ml-3 mr-5 mt-5 btn btn-dark btn-lg fa fa-arrow-circle-left">  Back</button></a>
			</div>
			<br>
			<div class="mb-5"></div>
	




{% endblock content %}

POSsystem/templates/login.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
	Login
{% endblock %}

{% block content %}

<div class="container">
	<br>
	<h2> Login Page :</h2>
	<div class="col-md-12 bg-dark mt-3 md-3 px-3 p-3">
		<form class="jumbotron border border-primary" action="{% url 'login' %}" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{form|crispy}}
			<input type="submit" name="Sign up" class="btn btn-primary">
		</form>
	</div>
</div>
{% endblock %}

POSsystem/templates/register.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
	Register
{% endblock %}

{% block content %}

<div class="container">
	<br>
	<h2> Register Page :</h2>
	<div class="col-md-12 bg-dark mt-3 md-3 px-3 p-3">
		<form class="jumbotron border border-primary" action="{% url 'register' %}" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{form|crispy}}
			<input type="submit" name="Sign up" class="btn btn-primary">
		</form>
	</div>
</div>
{% endblock %}